### ISSUE TITLE
Alternative Storage: Embedded database

### ISSUE THREAD

**Issue by xeoncross** [reconquest/shadowd#10]
Mongo is barely used in this application - yet requires a whole separate server instance. Consider migrating from a fixed mongo struct to an interface allowing an embedded Key/Value store (written in Go) to be used. Makes setup much easier and the performance should be improved for such a small database due to memory-mapped files and no network I/O.

- https://github.com/etcd-io/bbolt (Older, read optimized)
- https://github.com/dgraph-io/badger (Newer, write optimized)

**Comment by kovetskiy** [comment]
Hi! Thanks for the issue, a separated database is added to shadowd because it allows running multiple shadowd instances and it scales better than rsync'ing shadow entries from host to host. We picked MongoDB because it's very easy to configure & run a cluster of mongo instances and it will guarantee high availability of shadowd's database.

You can switch back to filesystem backend if you specify it in the configuration file 
```toml
[backend]
use = "filesystem"
dsn = "/"
```
then hash tables will be created in the dir specified by `--tables` flag and ssh keys will be placed at `--keys` flag.

The problem with bbolt and badger is that it's not possible to scale it horizontally (please correct me if I'm wrong).
